spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(FjJUNVivjn9diZ5vhPuHenotRfI6NUMS/9iWbjW9ntBm3iG36o0vvQ1dGjGYh0iKEjfH5z5EG2ZsaO6Zg25+kPusAIQmQbPkeHME4t7WWpxTVXggkja85APDA2B+TqDc)
    #    jdbc:mysql://localhost:3306/DB_NAME?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ENC(R+wP2zGeJr0nPCm6xsNtYQ==)
    password: ENC(HQlGe1wxUa1l8fe0ybauNQ==)
  mail:
    host: smtp.naver.com
    port: 587
    username: ENC(bxt2ytiq1IfahHvPSK9VO2iL9jb8RsHM)
    password: ENC(ORpnv/KIGLEzfoXzVgYuStkj3760UtDd)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: ENC(FNuQHfqr7zg3P/OJTDw87XUz286nZU+CK6Zp8eLy5yA=)
            client-secret: ENC(b5Z6JR5RLc2VR2qKfoB06FypOOBP8l69)
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email, gender, birthday
            client-name: Song
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

server:
  port: 443
  ssl:
    enabled: true
    key-store: /home/ubuntu/mall2/src/main/resources/bootsecurity.p12
    key-store-password: ENC(ByUYGffbX1Y93I3Yki4Ucw==)
    key-store-type: PKCS12
    key-alias: bootsecurity

upload:
  path: ENC(x8qrK5+qJcqsy0vquhEFR6CXNADt5v5AjZfSI4a9sZE0alcYXBLIQg==)

logging:
  level:
    org:
      springframework:
        security: DEBUG

portone:
  imp-key: ENC(VGyNDEvm8Om2Z50OiBgMOn02luMJgD3ToEeiD2DyCPQ=)
  imp-secret: ENC(SqbXXEhV80/ZtojU37qTsMX+xHij7uIvN6hxiDCMYAkzib2izEdR17ZkLLnHENpaU9VrPVMgTTNpS/wwhpXcYy5lFSvnC3lsPbrpW5kp25u9I9/SLOVWVlOCrUCxJXyK)
  api-secret: ENC(z6QdhGcVEWKp7qKiSXccqZdF05lGnM1vlYPt48LKfUAbBof+QpWE50KhrWWm9eM8CJrYL2h2YthTbedPbUgUuXunKfpw6UZnVixSAo63CABQXL7gvERBaWSu5bl5SrUV)
  store-id: ENC(J6SSNlpd814HcSGskWUBZWSwyp+W4z4Pn/plq0Qw1a86Snmk8kLJ9AvsFQM52/vkuHimBdswP58=)
  channel-key: ENC(TWbSHwgqBi/yoId10a76mzZ6nnXLR9T1YsXM5PpMaYmAcRWpQryUm9C3hxzAuT01lynCRdDIGOiuur6zO9Rhmw==)


