spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(NFnP6TqhlApT7qugXz8bh8rekjsLDqsSMtRY7a1xLSb4fcO1RtU53EhrVublL39JI1r3R/R2hxLw9pxAFOWt0e2pIFbSHkpsH0Kc6hUEh8SU7ao2mEWBz6NM1i6/dd/U)
    username: ENC(TiwRg7iI0QL/SURP799GEQ==)
    password: ENC(GRww4i+JOEcnHcihXnO0yw==)
  mail:
    host: smtp.naver.com
    port: 587
    username: ENC(XYGfsJTOQOJw+oj6hR+gt1f16jEOmJEu)
    password: ENC(5+CyQ8vVTmOfOMQjIg0fbTkppVfkXbMe)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: ENC(SVwX3wNtok4ScVHZhwf14jEmvzDSGlmHyjiPXlK7YZ0=)
            client-secret: ENC(PgsEu5NPT1KCRhDzMWXR3WUM/nLhh2mP)
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email, gender, birthday
            client-name: SongTest
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

upload:
  path: ENC(To+PRIHF3T1ZQzlAhsb/ZkWeVQzWMRd/x1snJB04SqAvV/UnrmhEXN1gaHcYMlQgiQF2e9AZtjM=)

portone:
  imp-key: ENC(pfdHvMxW93GuXPLyQ3VkYxTW8b8o9605hsB3yv6t3E4=)
  imp-secret: ENC(zOpN5weawYBUfdIP6YNSZFumXKP4GVeLkm2g598YMYj+CwDGWuXNuAiGhSNTcGbxyH/XTZnx7UWDiW50o7Wwpr6aET+x2bbv+2BieWvRulEp2ETooi+m4SV6yhIiUX5i)
  api_secret: ENC(NCKsFMe56TaOzHUtG3zdDD4UQIXXVnMbsY8fKtQNihE4i4aOqAiPl4sWqsk0xTQoktVgmvEqzfg9X9h0ei9j02VXK4M4JFKUtz7yBVMZ7BTJO6aEj41JMQMUjMwBjFUx)
  store-id: ENC(kwBIM9RaGji7bFZcE2gp2sjXpBS6Y5OxFktR+dy+m8bSnGhYHjp7r7Wv+DJqyygjJIKTtIZYha4=)
  channel-key: ENC(nDIuK/b1Z8kPFUjfKi/wNaNgGOYIprd4gWL+PlbQeEze/dio9ROvor5BiG1vmcMEmq9Zk1UCaTxScLq1Jesqsg==)


