spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(JOPdrI1cZVAvyvZt02KqO4nAIvfBx1oDZ8EUR03/qUK+PvQGlBOoacpk8drlTaSfMBqMCgA/6a/Ssr0SQauZHnQTkNwqn3Qa4WTe0TRunruPW776GQ4x6zVWK36CDR8V)
#    jdbc:mysql://localhost:3306/DB_NAME?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ENC(FxhxHpRvRfrWxchdhgjxZg==)
    password: ENC(IHwT264O1+wW6cJ9DjlqcQ==)
  mail:
    host: smtp.naver.com
    port: 587
    username: ENC(OU8T9PAJs8S4Xsc5VcFdVq5r82r7D5aR)
    password: ENC(PS3KrRW2uoTkHEZkjXhRRIDFoN18XyrB)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: ENC(eHJaqFjiBlMqdajMGffs1NgcZwRyzwUXQZFwr1gUoTM=)
            client-secret: ENC(g5gYLUlzZTq3hxq+hgz+vFQKmPSbOa5l)
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email, gender, birthday
            client-name: Song
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

upload:
  path: ENC(t3E7FLthCjhMgen5xcEs8nKa6hgWXzGo9xn3WBjzJZAnSBDmoE4bsnVO7gEtz4yjujX4SHqAsbg=)

logging:
  level:
    org:
      springframework:
        security: DEBUG

server:
  port: 443
  ssl:
    enabled: true
    key-store: src/main/resources/bootsecurity.p12
    key-store-password: ENC(seI8oCEpsDLGNOFer13CSQ==)
    key-store-type: PKCS12
    key-alias: bootsecurity

portone:
  imp-key: ENC(VRhFgoeDw8uh5RrElc7ZVsfRptSvDq2qt8sO00XjZJg=)
  imp-secret: ENC(Z6ylug0kRPSCp2NBU7WKNdHVHwNZeHLvWrdn8FLmrSoXHG3blxkH8hnF7T+RTPmab8oR9ev+VvLSJtN5/NblMXDm09FBB+w0xJvMg0Dx8j6WQVJI9lTimqVEJHfkajVB)
  api-secret: ENC(xNCW/plZ9qwTwWiVdg0NGhpEUCS01f1dEpK0j0rjAAuOrBsRZybSUgDR7bQ7UsNK43yp1qmWt4QSAqRMwOBt1EhDqCBVXyFV8Wg+mfYnpN4N5dg6eTsYQf8GV+56mWZq)
  store-id: ENC(coxjsHw114v8HQrD9a/HzyRJv3SPi8aTf32+5TEoSqbQ2rmAWs5JbQIR6W0dA6zvLm+rT+Zgp6o=)
  channel-key: ENC(ALmcZgwayxm9Ii9j1LzEtppRcf5Ka8aA7CucQfSUDYqerSR/pOgbUqbu3ZKZpQRsnqzl16uqb7IiayO4UqJ54A==)


